_target_: wrappers.AmplitudeDSIWrapper

net:
  _target_: models.dsi.DSI

  use_deepset: false
  sum_deepset: true
  use_invariants: true
  use_only_invariants: true
  
  hidden_channels_prenet: 128
  hidden_layers_prenet: 4
  out_dim_prenet_sep: 64
  hidden_channels_net: 128
  hidden_layers_net: 4