_target_: wrappers.AmplitudeKANWrapper

net:
  _target_: models.kan.KANnet

  in_shape: 20
  out_shape: 1

  hidden_channels: 30 
  hidden_layers: 5

  grid_size: 15
  spline_order: 3
  
  activation: 'gelu'
  num_groups: 1