#!/usr/bin/env python3
"""
finalize_sweep.py  —  Fill fidelity-grid gaps after a DyHPO sweep.

For each t_steps level in the fidelity grid, asks the surrogate which HP
configuration it predicts will perform best.  If that (hp_idx, t_steps) pair
has not been directly observed yet, generates an HTCondor job to run it.

Usage:
    python sweep/finalize_sweep.py --config sweeps/my_sweep/sweep_config.yaml
    python sweep/finalize_sweep.py --config sweeps/my_sweep/sweep_config.yaml --dry-run
"""

import argparse
import os
import subprocess
import sys

import yaml

_project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _project_dir not in sys.path:
    sys.path.insert(0, _project_dir)


def load_config(path):
    with open(path) as f:
        return yaml.safe_load(f)


def _sweep_dirs(cfg, sweep_name):
    if "sweep_dir" in cfg.get("paths", {}):
        d = os.path.join(cfg["paths"]["sweep_dir"], sweep_name)
        return d, d
    afs = os.path.join(cfg["paths"]["afs_sweep_dir"], sweep_name)
    eos = os.path.join(cfg["paths"]["eos_sweep_dir"], sweep_name)
    return afs, eos


def _scheduler(cfg):
    return cfg["cluster"].get("scheduler", "htcondor")


def _write_sh(job_name, cfg, afs_dir, config_path, hp_idx, t_steps):
    python_env   = cfg["paths"]["python_env"]
    project_dir  = cfg["paths"]["project_dir"]
    trial_script = os.path.join(project_dir, "sweep", "run_trial.py")

    eos_check = ""
    if "eos_sweep_dir" in cfg.get("paths", {}):
        eos_check = f"""\
_eos_ok=0
for _attempt in 1 2 3 4 5; do
    if [ -f {python_env} ]; then _eos_ok=1; break; fi
    echo "EOS not accessible (attempt ${{_attempt}}/5), retrying in 30s..."
    sleep 30
done
if [ "${{_eos_ok}}" -eq 0 ]; then echo "ERROR: EOS not accessible."; exit 1; fi

"""

    content = f"""\
#!/bin/bash
set -euo pipefail

{eos_check}source {python_env}

python {trial_script} \\
    --sweep-config {config_path} \\
    --trial-idx 0 \\
    --fixed-hp-idx {hp_idx} \\
    --fixed-t-steps {t_steps}
"""
    path = os.path.join(afs_dir, "jobs", f"{job_name}.sh")
    with open(path, "w") as f:
        f.write(content)
    os.chmod(path, 0o755)
    return path


def _env_setup_lines(cfg):
    setup_commands = cfg["paths"].get("setup_commands")
    if setup_commands:
        return "\n".join(setup_commands)
    return f"source {cfg['paths']['python_env']}"


def _write_slurm_script(job_name, cfg, sweep_dir, config_path, hp_idx, t_steps):
    cluster      = cfg["cluster"]
    project_dir  = cfg["paths"]["project_dir"]
    trial_script = os.path.join(project_dir, "sweep", "run_trial.py")
    mem_line = f"#SBATCH --mem={cluster['mem']}\n" if "mem" in cluster else ""

    content = f"""\
#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --partition={cluster["partition"]}
#SBATCH --account={cluster["account"]}
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:{cluster["request_gpus"]}
#SBATCH --cpus-per-task={cluster.get("cpus_per_task", 8)}
#SBATCH --time={cluster.get("time", "20:00:00")}
{mem_line}#SBATCH --output={sweep_dir}/output/{job_name}_%j.out
#SBATCH --error={sweep_dir}/error/{job_name}_%j.err

{_env_setup_lines(cfg)}

python {trial_script} \\
    --sweep-config {config_path} \\
    --trial-idx 0 \\
    --fixed-hp-idx {hp_idx} \\
    --fixed-t-steps {t_steps}
"""
    path = os.path.join(sweep_dir, "jobs", f"{job_name}.sh")
    with open(path, "w") as f:
        f.write(content)
    os.chmod(path, 0o755)
    return path


def _write_sub(job_name, cfg, afs_dir, sh_path):
    cluster      = cfg["cluster"]
    requirements = cluster.get("requirements", "True")
    extra        = "\n".join(cluster.get("extra_lines", []))
    if extra:
        extra += "\n"
    gpu_mem_line = (f"gpus_minimum_memory     = {cluster['gpus_minimum_memory']}\n"
                    if "gpus_minimum_memory" in cluster else "")

    content = f"""\
# HTCondor submission — finalize: {cfg['sweep_name']}, {job_name}
# Generated by finalize_sweep.py — do not edit manually

executable  = {sh_path}
output      = {afs_dir}/output/{job_name}.$(ClusterId).$(ProcId).out
error       = {afs_dir}/error/{job_name}.$(ClusterId).$(ProcId).err
log         = {afs_dir}/log/{job_name}.$(ClusterId).$(ProcId).log

request_gpus          = {cluster["request_gpus"]}
{gpu_mem_line}+JobFlavour           = "{cluster["job_flavour"]}"
requirements          = {requirements}
max_retries           = 3
{extra}
queue
"""
    path = os.path.join(afs_dir, "subs", f"{job_name}.sub")
    with open(path, "w") as f:
        f.write(content)
    return path


def main():
    parser = argparse.ArgumentParser(description="Fill DyHPO fidelity-grid gaps using surrogate predictions")
    parser.add_argument("--config",  required=True, help="Path to the frozen sweep_config.yaml in the AFS sweep dir")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    cfg        = load_config(args.config)
    sweep_name = cfg["sweep_name"]

    afs_dir, eos_dir = _sweep_dirs(cfg, sweep_name)

    state_path      = os.path.join(afs_dir, "dyhpo_state.pkl")
    eos_output_path = os.path.join(eos_dir, "dyhpo_surrogate")

    from sweep.dyhpo_sampler import DyHPOSampler
    sampler = DyHPOSampler.load(state_path, eos_output_path)

    print(f"Sweep: {sweep_name}")
    print(f"Querying surrogate for best predicted HP per combo...")

    best_per_combo = sampler.best_predicted_per_combo()

    if not best_per_combo:
        print("Surrogate model not trained yet — not enough observations to predict.")
        return

    to_fill = []
    for internal_combo, hp_idx in best_per_combo.items():
        t_steps = sampler._from_combo(internal_combo)
        to_fill.append((hp_idx, t_steps))

    print(f"Combos with a surrogate-predicted best that hasn't been run: {len(to_fill)}")

    if not to_fill:
        print("Nothing to do.")
        return

    scheduler = _scheduler(cfg)
    job_paths = []
    for hp_idx, t_steps in to_fill:
        job_name = f"fill_hp{hp_idx:04d}_t{t_steps}"
        print(f"  {job_name}")

        if not args.dry_run:
            if scheduler == "slurm":
                job_path = _write_slurm_script(job_name, cfg, afs_dir, args.config, hp_idx, t_steps)
            else:
                sh_path  = _write_sh(job_name, cfg, afs_dir, args.config, hp_idx, t_steps)
                job_path = _write_sub(job_name, cfg, afs_dir, sh_path)
            job_paths.append(job_path)

    if args.dry_run:
        print("\n[dry-run] Done.")
        return

    submit_cmd  = "sbatch" if scheduler == "slurm" else "condor_submit"
    hint_glob   = "jobs/fill_*.sh" if scheduler == "slurm" else "subs/fill_*.sub"
    ans = input(f"\nSubmit {len(job_paths)} fill-gap jobs ({scheduler})? (y/N): ").strip().lower()
    if ans == "y":
        submitted = 0
        for job_path in job_paths:
            try:
                subprocess.run([submit_cmd, job_path], check=True)
                submitted += 1
            except subprocess.CalledProcessError as e:
                print(f"  Failed: {job_path}: {e}", file=sys.stderr)
        print(f"Submitted {submitted}/{len(job_paths)} jobs.")
    else:
        print(f"\nSubmit later with:")
        print(f"  for f in {afs_dir}/{hint_glob}; do {submit_cmd} $f; done")


if __name__ == "__main__":
    main()
