#!/usr/bin/env python3
"""
generate_sweep.py  —  Initialise an Optuna study and generate HTCondor job files.

Usage (from lxplus login node or locally):
    python sweep/generate_sweep.py --config sweep/sweep_config.yaml
    python sweep/generate_sweep.py --config sweep/sweep_config.yaml --dry-run
    python sweep/generate_sweep.py --config sweep/sweep_config.yaml --n-trials 60

Re-running with a higher --n-trials extends an existing sweep without disturbing
completed trials (load_if_exists=True).
"""

import argparse
import os
import subprocess
import sys

import optuna
import yaml
from optuna.storages import JournalStorage
from optuna.storages.journal import JournalFileBackend

optuna.logging.set_verbosity(optuna.logging.WARNING)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_config(path):
    with open(path) as f:
        return yaml.safe_load(f)


def setup_dirs(cfg, sweep_name):
    afs = os.path.join(cfg["paths"]["afs_sweep_dir"], sweep_name)
    eos = os.path.join(cfg["paths"]["eos_sweep_dir"], sweep_name)
    for d in [
        os.path.join(afs, "jobs"),
        os.path.join(afs, "subs"),
        os.path.join(afs, "output"),
        os.path.join(afs, "error"),
        os.path.join(afs, "log"),
        os.path.join(eos, "results"),
    ]:
        os.makedirs(d, exist_ok=True)
    return afs, eos


def init_study(cfg, afs_dir):
    # Journal lives on AFS, not EOS — AFS has proper POSIX advisory locking.
    # EOS does not support fcntl locks reliably, causing corruption under concurrency.
    journal_path = os.path.join(afs_dir, "optuna_journal.log")
    storage = JournalStorage(JournalFileBackend(journal_path))
    sampler = optuna.samplers.TPESampler(
        n_startup_trials=cfg["optuna"]["n_startup_trials"],
        seed=42,
    )
    study = optuna.create_study(
        study_name=cfg["sweep_name"],
        storage=storage,
        direction=cfg["optuna"]["direction"],
        sampler=sampler,
        load_if_exists=True,
    )
    return study, journal_path


def write_sh(i, cfg, afs_dir, config_abs_path):
    project_dir = cfg["paths"]["project_dir"]
    python_env  = cfg["paths"]["python_env"]
    trial_script = os.path.join(project_dir, "sweep", "run_trial.py")

    content = f"""\
#!/bin/bash
set -euo pipefail

source {python_env}

python {trial_script} \\
    --sweep-config {config_abs_path} \\
    --trial-idx {i}
"""
    path = os.path.join(afs_dir, "jobs", f"trial_{i:04d}.sh")
    with open(path, "w") as f:
        f.write(content)
    os.chmod(path, 0o755)
    return path


def write_sub(i, cfg, afs_dir, sh_path):
    cluster = cfg["cluster"]
    requirements = cluster.get("requirements", "True")
    extra = "\n".join(cluster.get("extra_lines", []))
    if extra:
        extra = extra + "\n"

    gpu_mem_line = ""
    if "gpus_minimum_memory" in cluster:
        gpu_mem_line = f"gpus_minimum_memory     = {cluster['gpus_minimum_memory']}\n"

    name = f"trial_{i:04d}"
    content = f"""\
# HTCondor submission — sweep: {cfg["sweep_name"]}, trial {i:04d}
# Generated by generate_sweep.py — do not edit manually

executable  = {sh_path}
output      = {afs_dir}/output/{name}.$(ClusterId).$(ProcId).out
error       = {afs_dir}/error/{name}.$(ClusterId).$(ProcId).err
log         = {afs_dir}/log/{name}.$(ClusterId).$(ProcId).log

request_gpus          = {cluster["request_gpus"]}
{gpu_mem_line}+JobFlavour           = "{cluster["job_flavour"]}"
requirements          = {requirements}
{extra}
queue
"""
    path = os.path.join(afs_dir, "subs", f"{name}.sub")
    with open(path, "w") as f:
        f.write(content)
    return path


def prompt_yes_no(msg):
    ans = input(f"\n{msg} (y/N): ").strip().lower()
    return ans == "y"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def next_available_name(base_name, afs_sweep_dir):
    """Return base_name if unused, otherwise base_name with an incremented suffix.

    Looks for an existing optuna_journal.log under afs_sweep_dir/base_name.
    If found, increments the trailing _NNN number (adds _002 if none present).
    """
    import re
    def journal_exists(name):
        return os.path.exists(os.path.join(afs_sweep_dir, name, "optuna_journal.log"))

    if not journal_exists(base_name):
        return base_name

    # Try to find and increment a trailing number, e.g. _001 → _002
    m = re.search(r"^(.*?)(_(\d+))$", base_name)
    if m:
        stem, _, num = m.group(1), m.group(2), m.group(3)
        n = int(num)
        width = len(num)
    else:
        stem = base_name
        n = 1
        width = 3

    while True:
        n += 1
        candidate = f"{stem}_{n:0{width}d}"
        if not journal_exists(candidate):
            return candidate


def main():
    parser = argparse.ArgumentParser(description="Generate Bayesian HPO sweep jobs")
    parser.add_argument("--config", required=True, help="Path to sweep_config.yaml")
    parser.add_argument("--dry-run", action="store_true",
                        help="Generate files but do not initialise the Optuna study or submit")
    parser.add_argument("--n-trials", type=int, default=None,
                        help="Override n_trials from config")
    parser.add_argument("--extend", action="store_true",
                        help="Extend an existing sweep instead of creating a new one. "
                             "Without this flag, if the sweep name already exists a new "
                             "name with an incremented suffix is used automatically.")
    args = parser.parse_args()

    config_abs_path = os.path.abspath(args.config)
    cfg = load_config(config_abs_path)
    n_trials = args.n_trials if args.n_trials is not None else cfg["optuna"]["n_trials"]

    # Auto-increment sweep name unless --extend is passed
    base_name = cfg["sweep_name"]
    afs_sweep_dir = cfg["paths"]["afs_sweep_dir"]
    if args.extend:
        sweep_name = base_name
        print(f"Extending existing sweep: {sweep_name}")
    else:
        sweep_name = next_available_name(base_name, afs_sweep_dir)
        if sweep_name != base_name:
            print(f"Sweep '{base_name}' already exists — using '{sweep_name}' instead.")
            print(f"  (Pass --extend to add trials to the existing sweep.)")

    cfg["sweep_name"] = sweep_name
    print(f"Sweep: {sweep_name}  |  n_trials: {n_trials}")

    afs_dir, eos_dir = setup_dirs(cfg, sweep_name)
    print(f"  AFS dir : {afs_dir}")
    print(f"  EOS dir : {eos_dir}")

    # Save a frozen copy of the config in the sweep dir.
    # This means analyze_sweep.py can be pointed at the sweep dir directly —
    # no need to remember which config file was used.
    # IMPORTANT: save the modified cfg (with correct sweep_name), not the original.
    saved_config = os.path.join(afs_dir, "sweep_config.yaml")
    if not (args.dry_run and os.path.exists(saved_config)):
        import shutil
        shutil.copy2(config_abs_path, saved_config)
        with open(saved_config, "w") as f:
            yaml.dump(cfg, f)
        print(f"  Config saved : {saved_config}")

    if not args.dry_run:
        study, journal_path = init_study(cfg, afs_dir)
        existing = len(study.trials)
        print(f"  Optuna journal : {journal_path}")
        print(f"  Existing trials: {existing}")
    else:
        print("  [dry-run] Skipping Optuna study initialisation")

    # Generate job files — .sh scripts reference the saved config copy so they
    # keep using the correct config even if the original is edited for a new sweep.
    sub_paths = []
    for i in range(n_trials):
        sh_path  = write_sh(i, cfg, afs_dir, saved_config)
        sub_path = write_sub(i, cfg, afs_dir, sh_path)
        sub_paths.append(sub_path)

    print(f"\nGenerated {n_trials} job + sub pairs under:")
    print(f"  jobs : {os.path.join(afs_dir, 'jobs')}")
    print(f"  subs : {os.path.join(afs_dir, 'subs')}")

    if args.dry_run:
        print("\n[dry-run] Done. Inspect the generated files above before submitting.")
        return

    # Optionally submit
    auto = cfg["cluster"].get("auto_submit", False)
    if auto or prompt_yes_no("Submit all jobs to HTCondor now?"):
        submitted = 0
        for sub_path in sub_paths:
            try:
                subprocess.run(["condor_submit", sub_path], check=True)
                submitted += 1
            except subprocess.CalledProcessError as e:
                print(f"  Failed to submit {sub_path}: {e}", file=sys.stderr)
        print(f"\nSubmitted {submitted}/{n_trials} jobs.")
    else:
        print(f"\nSkipping submission. Submit later with:")
        print(f"  for f in {afs_dir}/subs/trial_*.sub; do condor_submit $f; done")


if __name__ == "__main__":
    main()
