cluster:
  scheduler: slurm
  auto_submit: false
  partition: gpu_p2
  account: itg@v100
  request_gpus: 1
  cpus_per_task: 8
  time: "10:00:00"

paths:
  sweep_dir: /lustre/fswork/projects/rech/itg/ulm49ia/Foundational_Amplitudes/sweeps
  project_dir: /lustre/fswork/projects/rech/itg/ulm49ia/Foundational_Amplitudes
  setup_commands:
    - "module load anaconda-py3/2023.09"
    - "conda activate /lustre/fswork/projects/rech/itg/ulm49ia/conda/envs/foundational"

sweep_name: finetune_nlovirt_001
n_trials: 40

dyhpo:
  n_candidates: 200
  seed: 42
  n_startup: 15
  total_budget: 5000

fidelity_schedule:
  t_steps: [1000, 5000, 20000]

fixed_params:
  data.data_path: /lustre/fswork/projects/rech/itg/ulm49ia/Foundational_Amplitudes/data/
  data.dataset: '[ee_uu_nlo_virt_e4, ee_ttbar_nlo_virt_e4]'
  data.amp_orders: '[[1,0],[1,0]]'
  data.subsample: null
  fine_tune.pretrained_path: /lustre/fswork/projects/rech/itg/ulm49ia/Foundational_Amplitudes/runs/many_datasets_006/trial_0174/models/model_run0_best.pt.gz
  fine_tune.layer_decay: 1.0
  model: lloca
  model.net.num_blocks: 8
  model.net.num_heads: 16
  plot: 'true'
  training.lr: 0.008322839
  training.batchsize: 8192
  training.get_ID: 'false'
  training.regularization: L2
  training.regularization_lambda: 4.189923e-09
  training.save_intermediate: 'false'
  training.scheduler: CosineAnnealingLR
  training.validate_every_n_steps: 100

search_space:
- name: fine_tune.lr_scale
  type: float_log
  low: 0.001
  high: 1.0
- name: training.cosanneal_warmup_frac
  type: float_uniform
  low: 0.0
  high: 0.2
- name: training.cosanneal_eta_min
  type: float_log
  low: 1.0e-11
  high: 1.0e-04
