cluster:
  account: itg@v100
  partition: gpu_p2
  request_gpus: 1
  cpus_per_task: 8
  scheduler: slurm
  time: 06:00:00
  auto_submit: false
dyhpo:
  n_candidates: 300
  n_startup: 8
  seed: 42
  total_budget: 10000
fidelity_schedule:
  t_steps:
  - 5000
n_trials: 15
fixed_params:
  data.source: recipes
  data.processes_file: /lustre/fswork/projects/rech/itg/ulm49ia/Foundational_Amplitudes/recipes/scan_bigrun.yaml
  data.require_cache: 'true'
  data.train_subsample: 2000
  data.eval_subsample: 500
  data.preprocess_per_dataset: 'true'
  data.seed: 42
  data.use_PIDs: 'false'
  data.spin_onehot: 'true'
  data.color_onehot: 'true'
  data.prop_is_massless: 'true'
  data.standardize_props: 'true'
  model: lloca
  seed: 42
  training.batchsize: 1024
  evaluation.batchsize: 4096
  training.loss_aggregation: geometric_mean
  training.regularization: L2
  training.scheduler: CosineAnnealingLR
  training.get_ID: 'false'
  training.save_intermediate: 'false'
  training.validate_every_n_steps: 500
  training.dtype: float32
  plot: 'false'
  use_mlflow: 'false'
  data.mass_from_momenta: 'false'
  data.coupling_scalars: 'false'
  model.use_diagrams: 'false'
paths:
  project_dir: /lustre/fswork/projects/rech/itg/ulm49ia/Foundational_Amplitudes
  sweep_dir: /lustre/fswork/projects/rech/itg/ulm49ia/Foundational_Amplitudes/sweeps/scan_ab
  setup_commands:
  - module load anaconda-py3/2023.09
  - source /gpfslocalsup/pub/anaconda-py3/2023.09/etc/profile.d/conda.sh
  - conda activate /lustre/fswork/projects/rech/itg/ulm49ia/conda/envs/foundational
sweep_name: scan_ab_off
range_extension:
  enabled: false
search_space:
- name: training.lr
  type: float_log
  low: 0.0001
  high: 0.01
- name: training.regularization_lambda
  type: float_log
  low: 1.0e-11
  high: 1.0e-06
- name: training.cosanneal_warmup_frac
  type: float_uniform
  low: 0.0
  high: 0.2
- name: training.cosanneal_eta_min
  type: float_log
  low: 1.0e-11
  high: 1.0e-06
- name: training.ema_decay
  type: float_uniform
  low: 0.9
  high: 0.9999
