#!/usr/bin/env bash
# Rebuild every figure that docs/results.tex includes, from data already on disk. CPU only,
# login-node safe.
#
# WHY THIS FILE EXISTS. Several figures in results.tex were produced by ad-hoc one-off
# invocations that were never written down, so when the eval data moved or a worktree was
# deleted there was no way to reproduce them. Every figure now has its exact command
# recorded here. Add a line here whenever you add a figure -- a plotting script whose
# invocation is undocumented is one worktree deletion away from being unreproducible.
#
# Everything included by results.tex now rebuilds from data on disk. l2_poly_keep was the
# lone exception -- its 12-trial DyHPO sweep had been destroyed with a worktree -- and the
# sweep was re-run on the trunk (sweeps/l2_poly_uugg, 12 trials, ~7.4 GPU-h), so that figure
# builds again. plot_poly_keep.py still exits non-zero if the results directory is empty,
# rather than emitting the blank panel that once shipped into the document.
#
# Usage:  bash scripts/rebuild_figures.sh [pattern]
#         pattern filters by output basename, e.g. `bash scripts/rebuild_figures.sh l2_`
set -uo pipefail
cd /sps/lpnhe/jiturrizaramirez01/Foundational_Amplitudes
PY=/sps/lpnhe/jiturrizaramirez01/Foundational_Amplitudes/.venv/bin/python
D=analysis/divergences
FILTER="${1:-}"

ok=0; fail=0; skip=0; warn=0
run() {  # run <output-basename> <command...>
  local name="$1"; shift
  if [ -n "$FILTER" ] && [[ "$name" != *"$FILTER"* ]]; then skip=$((skip+1)); return; fi
  if out=$("$@" 2>&1); then
    echo "  ok      $name"; ok=$((ok+1))
    # Surface plot_style's squeezed-panel warning. run() swallows stdout on success, which is
    # how six figures with 0.2-0.9in panels were reported "ok" while shouting about it.
    if printf '%s' "$out" | grep -q '!!'; then
      printf '%s' "$out" | grep '!!' | sed 's/^ */          WARN /'
      warn=$((warn+1))
    fi
  else
    echo "  FAILED  $name"
    echo "$out" | tail -3 | sed 's/^/            /'
    fail=$((fail+1))
  fi
}

echo "== divergence sampling =="
run l2_uugg_perdecade        $PY $D/plot_l2_uugg.py
run l2_uugg_perdecade_abs    $PY $D/plot_l2_uugg_abs.py
run l2_uugg_gamma            $PY $D/plot_l2_uugg_gamma.py
run l2_gamma_response_ext    $PY $D/plot_gamma_response.py
run l2_saturation            $PY $D/plot_saturation.py
# emits TWO figures: the 3-process sigma/RMSE panels and the pre-flight diagnostic
run l2_sigma_vs_divergence   $PY $D/plot_sigma_vs_divergence.py
run l2_poly_keep             $PY $D/plot_poly_keep.py
run l2_bbbarg                $PY $D/plot_l2_bbbarg.py
run l2_bbb_sweep             $PY $D/plot_bbb_sweep.py
run soft_vs_coll_addback     $PY $D/plot_soft_vs_coll.py
run deep_sampling_fraction   $PY $D/plot_fraction_sweep.py
run deep_sampling_uniform    $PY $D/plot_deep_sampling.py
run eeuu_flatlogm_resonance  $PY $D/plot_eeuu_resonance.py
run eeuu_genmix_fraction     $PY $D/plot_genmix_sweep.py

# add-back curves. heldout_eval_ft_f100.npz was once overwritten by an unrelated eval,
# losing `cut`/`x_gmin` and breaking both of these; it is regenerated by
# analysis/divergences/eval_heldout_addback.sh (GPU, ~4 min for all five tags).
run addback_curve            $PY $D/plot_addback.py --tags 000,005,015,050,100 \
                                 --out_base $D/figs/addback_curve \
                                 --summary_out $D/heldout_eval_summary.json
run addback_curve_uugg       $PY $D/plot_addback.py --tags 000,005,015,050,100 \
                                 --npz_prefix heldout_eval_uugg_f \
                                 --out_base $D/figs/addback_curve_uugg \
                                 --summary_out $D/heldout_eval_uugg_summary.json \
                                 --process '$e^+e^-\to u\bar u gg$'

echo "== multi-run comparisons =="
run l2_uug_multiscale        $PY $D/plot_l2_compare.py --regions \
                                 --out $D/figs/l2_uug_multiscale \
                                 --process '$e^+e^-\to u\bar u g$' \
                                 --npz 'uniform=heldout_eval_uug_base_s0' \
                                       '$\sigma$, $\gamma=1$=heldout_eval_uug_sigma_s0' \
                                       '$\sigma$, $\gamma=3$=heldout_eval_uug_g3_s0'
run l2_uuggg_perdecade       $PY $D/plot_l2_compare.py \
                                 --out $D/figs/l2_uuggg_perdecade \
                                 --process '$e^+e^-\to u\bar u ggg$' \
                                 --npz 'uniform=heldout_eval_uuggg_base_s0' \
                                       '$\sigma$, $\gamma=1$=heldout_eval_uuggg_sigma_s0' \
                                       '$\sigma$, $\gamma=3$=heldout_eval_uuggg_g3_s0' \
                                       '$\sigma$, $\gamma=10$=heldout_eval_uuggg_g10_s0' \
                                       '$\sigma$, $\gamma=20$=heldout_eval_uuggg_g20_s0'
run l2_uugg_bbb_vs_het       $PY $D/plot_l2_compare.py \
                                 --out $D/figs/l2_uugg_bbb_vs_het \
                                 --process '$e^+e^-\to u\bar u gg$' \
                                 --npz 'uniform=heldout_eval_base_s0' \
                                       'het $\sigma$, $\gamma=3$=heldout_eval_g3_s0' \
                                       'BBB $\sigma$, $\gamma=3$=heldout_eval_uugg_bbb_g3_s0'

echo "== sigma reweighting (Q2) =="
# Both read the q2rw_eval_*.npz on disk; the shared metric layer is $D/q2_metrics.py, which
# replaces the lost recompute_q2_logflat.py that results.tex used to cite.
run q2_logflat               $PY $D/plot_q2_logflat.py
run q2_rankmag               $PY $D/plot_q2_rankmag.py

echo "== feature levers =="
# Reads each arm's plots_0/per_process_metrics.json from compare_models/_levers_ab/,
# produced by compare_models/run_levers_ab.sh (GPU, 2-task array).
run levers_offshell_ab       $PY compare_models/plot_levers_ab.py

echo "== HPO optima =="
H=analysis/hpo_optima
run hpo_optima_summary       $PY $H/make_fig.py       $H/hpo_optima.json $H/hpo_optima_summary
run lr_2d_disentangled       $PY $H/make_fig_2d.py    $H/hpo_optima.json $H/lr_2d_disentangled
run lr_vs_iterations         $PY $H/make_fig_iters.py $H/hpo_optima.json $H/lr_vs_iterations_by_regime

echo "== IR residual maps =="
# Each make_ir.py call also emits <base>_dalitz and <base>_collinear, both of which
# results.tex includes; the npz comes from eval_heldout_addback.sh / extract_ir.py.
run heldout_resid_f000       $PY $D/make_ir.py --npz $D/heldout_eval_ft_f000.npz \
                                 --label 'ee->uug hold-out f=0' \
                                 --out_base $D/figs/heldout_resid_f000
run heldout_resid_f100       $PY $D/make_ir.py --npz $D/heldout_eval_ft_f100.npz \
                                 --label 'ee->uug hold-out f=1' \
                                 --out_base $D/figs/heldout_resid_f100
run ir3d                     $PY $D/make_ir_3d.py
run ir_pretrain_uug          $PY $D/make_ir.py \
                                 --npz $D/preds_ir_pretrain8_ee_uug_91-1000GeV_amplitudes.npz \
                                 --label 'ee->uug' --out_base $D/figs/ir_pretrain_uug
run ir_pretrain_uugg         $PY $D/make_ir.py \
                                 --npz $D/preds_ir_pretrain8_ee_uugg_91-1000GeV_amplitudes.npz \
                                 --label 'ee->uugg' --out_base $D/figs/ir_pretrain_uugg
# fig:div_gg is make_plots.py's 3x3 (truth/model/error, projections + pred-vs-true, collinear
# ramp), NOT make_3d.py's two 3-D surfaces. This line previously pointed at make_3d.py with the
# make_plots basename, so it silently OVERWROTE the figure the caption describes with a
# different plot entirely. The two generators own separate basenames: phase_space_<tag> for
# make_plots.py, phase_space_3d_<tag> for make_3d.py.
run phase_space_pretrain_aa  $PY $D/make_plots.py \
                                 --npz $D/preds_pretrain8_ee_aa_10-1000GeV_amplitudes.npz \
                                 --label '$e^+e^-\to\gamma\gamma$' \
                                 --out_base $D/figs/phase_space_pretrain_aa
run phase_space_3d_pretrain_aa $PY $D/make_3d.py \
                                 --npz $D/preds_pretrain8_ee_aa_10-1000GeV_amplitudes.npz \
                                 --label '$e^+e^-\to\gamma\gamma$' \
                                 --out_base $D/figs/phase_space_3d_pretrain_aa

echo "== fine-tune methods =="
# Reads each sweep's SAVED outer config (sweeps/<name>/sweep_config.yaml), not sweep/*.yaml.
run finetune_methods         $PY sweep/compare_finetune_methods.py --out-dir docs/figs \
                                 --configs sweeps/finetune_scaling_virt_002/sweep_config.yaml \
                                           sweeps/finetune_lora_scaling_virt/sweep_config.yaml \
                                           sweeps/finetune_ewc_scaling_virt/sweep_config.yaml \
                                           sweeps/finetune_freeze_scaling_virt/sweep_config.yaml \
                                           sweeps/finetune_resethead_scaling_virt/sweep_config.yaml
# Multi-page PDF (results.tex includes pages 2-6); PdfPages emits no .png counterpart.
run phase1_scaling           $PY sweep/analyze_pretraining_scaling.py --dry-run

echo "== scaling =="
run compute_scan_wt          $PY analysis/scaling_compute/build_compute_scan_walltime.py
run alpha_vs_multiplicity    $PY analysis/scaling_compute/alpha_vs_multiplicity_overlay.py \
                                 analysis/scaling_compute/alpha_vs_multiplicity_overlay

# --- shadowing check ---------------------------------------------------------
# docs/figs is FIRST in results.tex \graphicspath, so a stale copy there silently wins
# over a freshly generated one elsewhere. That happened to four figures. Fail loudly.
shadow=0
for f in docs/figs/*.pdf; do
  [ -e "$f" ] || continue
  b=$(basename "$f" .pdf)
  other=$(ls analysis/hpo_optima/$b.pdf analysis/divergences/figs/$b.pdf \
             analysis/divergences/$b.pdf analysis/scaling_compute/$b.pdf \
             compare_models/_levers_ab/$b.pdf compare_models/figs/$b.pdf \
             plots/$b.pdf 2>/dev/null | head -1)
  if [ -n "$other" ]; then
    echo "  SHADOWED  docs/figs/$b.pdf hides $other -- delete the docs/figs copy"
    shadow=$((shadow+1))
  fi
done

echo
echo "rebuilt $ok, failed $fail, skipped $skip, shadowed $shadow, squeezed $warn"

# Panels included two per line have to ADD UP to less than \\textwidth or LaTeX quietly drops
# the last one onto its own line -- a real layout regression that nothing else warns about.
echo
$PY scripts/check_tex_figure_rows.py || rows_bad=1

[ "$fail" -gt 0 ] || [ "$shadow" -gt 0 ] || [ -n "${rows_bad:-}" ] && exit 1
exit 0
